services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: assessment_db
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  jupyter:
    image: jupyter/pyspark-notebook:latest
    ports:
      - "8888:8888"
    environment:
      JUPYTER_ENABLE_LAB: "yes"
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./requirements.txt:/home/jovyan/requirements.txt
    depends_on:
      - postgres
    command: >
      bash -c "pip install --no-cache-dir -r /home/jovyan/requirements.txt &&
      start-notebook.sh --NotebookApp.token=''"